<a href="https://colab.research.google.com/github/akhil2kv/Dash_financial_dashboard/blob/UAT/UAT_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
!pip install plotly dash dash-bootstrap-components alpha-vantage --quiet

In [41]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input,Output
import dash_bootstrap_components as dbc
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from alpha_vantage.timeseries import TimeSeries

In [12]:
key = '920CRW9UQMJBPZHM'
ts = TimeSeries(key=key,output_format="pandas")
ttm_data ,ttm_meta_data = ts.get_intraday(symbol='TTM',interval='1min',outputsize='compact')
ttm_data.head(5)

                     1. open  2. high  3. low  4. close  5. volume
date
2022-03-04 16:55:00  26.3100    26.31   26.02     26.12      895.0
2022-03-04 16:10:00  26.3500    26.35   26.35     26.35      150.0
2022-03-04 16:02:00  26.4400    26.44   26.44     26.44      279.0
2022-03-04 16:01:00  26.3300    26.44   26.33     26.33     5385.0
2022-03-04 16:00:00  26.3399    26.34   26.29     26.31    41067.0

In [21]:
df = ttm_data.copy( ) #make copy of the DaraFrame so that original will be preserved this way
df = df.transpose() # make a transpose of the DataFrame for better working 
df.head()

date,2022-03-04 16:55:00,2022-03-04 16:10:00,2022-03-04 16:02:00,2022-03-04 16:01:00,2022-03-04 16:00:00,2022-03-04 15:59:00,2022-03-04 15:58:00,2022-03-04 15:57:00,2022-03-04 15:56:00,2022-03-04 15:55:00,...,2022-03-04 14:31:00,2022-03-04 14:30:00,2022-03-04 14:29:00,2022-03-04 14:28:00,2022-03-04 14:26:00,2022-03-04 14:25:00,2022-03-04 14:24:00,2022-03-04 14:23:00,2022-03-04 14:22:00,2022-03-04 14:20:00
1. open,26.31,26.35,26.44,26.33,26.3399,26.355,26.340,26.330,26.33,26.315,...,26.015,26.02,26.04,26.03,26.0407,26.05,26.040,26.035,26.03,26.02
2. high,26.31,26.35,26.44,26.44,26.3400,26.360,26.360,26.350,26.35,26.340,...,26.020,26.03,26.04,26.04,26.0600,26.05,26.055,26.050,26.03,26.02
3. low,26.02,26.35,26.44,26.33,26.2900,26.330,26.340,26.320,26.32,26.300,...,26.000,26.01,26.03,26.02,26.0407,26.04,26.040,26.030,26.01,26.02
4. close,26.12,26.35,26.44,26.33,26.3100,26.330,26.355,26.345,26.33,26.330,...,26.020,26.02,26.04,26.04,26.0600,26.04,26.055,26.030,26.03,26.02
5. volume,895.00,150.00,279.00,5385.00,41067.0000,17135.000,11524.000,9899.000,12058.00,19604.000,...,1737.000,1562.00,790.00,1703.00,661.0000,1519.00,701.000,1892.000,2148.00,479.00

In [22]:
df.rename(index={"1. open":"open", "2. high":"high", "3. low":"low",
                 "4. close":"close","5. volume":"volume"},inplace=True) # just renaming to proper formats

df=df.reset_index() # converting multi-index into standard index format 
df=df.rename(columns={'index':'indicator'}) # renaming index column
df.head(5)

date,indicator,2022-03-04 16:55:00,2022-03-04 16:10:00,2022-03-04 16:02:00,2022-03-04 16:01:00,2022-03-04 16:00:00,2022-03-04 15:59:00,2022-03-04 15:58:00,2022-03-04 15:57:00,2022-03-04 15:56:00,...,2022-03-04 14:31:00,2022-03-04 14:30:00,2022-03-04 14:29:00,2022-03-04 14:28:00,2022-03-04 14:26:00,2022-03-04 14:25:00,2022-03-04 14:24:00,2022-03-04 14:23:00,2022-03-04 14:22:00,2022-03-04 14:20:00
0,open,26.31,26.35,26.44,26.33,26.3399,26.355,26.340,26.330,26.33,...,26.015,26.02,26.04,26.03,26.0407,26.05,26.040,26.035,26.03,26.02
1,high,26.31,26.35,26.44,26.44,26.3400,26.360,26.360,26.350,26.35,...,26.020,26.03,26.04,26.04,26.0600,26.05,26.055,26.050,26.03,26.02
2,low,26.02,26.35,26.44,26.33,26.2900,26.330,26.340,26.320,26.32,...,26.000,26.01,26.03,26.02,26.0407,26.04,26.040,26.030,26.01,26.02
3,close,26.12,26.35,26.44,26.33,26.3100,26.330,26.355,26.345,26.33,...,26.020,26.02,26.04,26.04,26.0600,26.04,26.055,26.030,26.03,26.02
4,volume,895.00,150.00,279.00,5385.00,41067.0000,17135.000,11524.000,9899.000,12058.00,...,1737.000,1562.00,790.00,1703.00,661.0000,1519.00,701.000,1892.000,2148.00,479.00

In [23]:
df = pd.melt(df,id_vars='indicator',var_name='date',value_name='rate')
df.head()

  indicator                date    rate
0      open 2022-03-04 16:55:00   26.31
1      high 2022-03-04 16:55:00   26.31
2       low 2022-03-04 16:55:00   26.02
3     close 2022-03-04 16:55:00   26.12
4    volume 2022-03-04 16:55:00  895.00

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   indicator  500 non-null    object
 1   date       500 non-null    datetime64[ns]
 2   rate       500 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 11.8+ KB

In [29]:
df = df[df['indicator']!= 'volume']

In [30]:
df.head()

  indicator                date   rate
0      open 2022-03-04 16:55:00  26.31
1      high 2022-03-04 16:55:00  26.31
2       low 2022-03-04 16:55:00  26.02
3     close 2022-03-04 16:55:00  26.12
5      open 2022-03-04 16:10:00  26.35

In [32]:
px.scatter(df,x='date',y='rate',color='indicator')

In [ ]:
df

In [34]:
df.to_csv('data.csv',index=False) # saving the wrangled data to file

In [36]:
df= pd.read_csv('https://raw.githubusercontent.com/akhil2kv/Dash_financial_dashboard/1c1eda0dfc8fe870a6c67e32e3b72b362ba9a5bd/data.csv',index_col=0)

In [37]:
df.head()

  indicator                 date   rate
0      open  2022-03-04 16:55:00  26.31
1      high  2022-03-04 16:55:00  26.31
2       low  2022-03-04 16:55:00  26.02
3     close  2022-03-04 16:55:00  26.12
5      open  2022-03-04 16:10:00  26.35

In [40]:
app = dash.Dash(__name__,external_stylesheets=[dbc.themes.BOOTSTRAP])
                # meta_tags=[{'name': 'viewport',
                #             'content': 'width=device-width, initial-scale=1.0'}]

In [45]:
app.layout = dbc.Container([
                            dbc.Row([
                                     dbc.Col([
                                           dbc.Card([
                                                     dbc.CardImg(
                                                                  src="tataimg.png",
                                                                  top=True,
                                                                  style={"width": "6rem"}
                                                     ),
                                                     dbc.CardBody([
                                                                   dbc.Row([
                                                                       dbc.Col([
                                                                                html.P(" Change (1D) ")
                                                                       ]),
                                                                       dbc.Col([
                                                                                dcc.Graph(id='indicator-graph',figure={},config={'displayModeBar':False})
                                                                       ])     
                                                                   ]),
                                                                   dbc.Row([
                                                                            
                                                                   ]),
                                                                   dbc.Row([
                                                                            
                                                                   ]),
                                                                   dbc.Row([
                                                                            
                                                                   ])
                                                     ])
                                           ])   
                                     ])
                            ])
])






if __name__=='__main__':
    app.run_server(debug=True, port=8000)

Dash is running on http://127.0.0.1:8000/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

SystemExit: ignored

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning:

To exit: use 'exit', 'quit', or Ctrl-D.

In [47]:
dff = df[df.indicator.isin(['high'])]

In [ ]:
app.layout = dbc.Container([
    dbc.Row([
        dbc.Col([
            dbc.Card(
                [
                    dbc.CardImg(
                        src="tataimg.png",
                        top=True,
                        style={"width": "6rem"},
                    ),

                    dbc.CardBody([
                        dbc.Row([
                            dbc.Col([
                                html.P("CHANGE (1D)")
                            ]),

                            dbc.Col([
                                dcc.Graph(id='indicator-graph', figure={},
                                          config={'displayModeBar':False})
                            ])
                        ]),

                        dbc.Row([
                            dbc.Col([
                                dcc.Graph(id='daily-line', figure={},
                                          config={'displayModeBar':False})
                            ])
                        ]),

                        dbc.Row([
                            dbc.Col([
                                dbc.Button("SELL"),
                            ]),

                            dbc.Col([
                                dbc.Button("BUY")
                            ])
                        ]),

                        dbc.Row([
                            dbc.Col([
                                dbc.Label(id='low-price', children="12.237"),
                            ]),
                            dbc.Col([
                                dbc.Label(id='high-price', children="13.418"),
                            ])
                        ])
                    ]),
                ],
                style={"width": "24rem"},
                className="mt-3"
            )
        ], width=6)
    ], justify='center'),

    dcc.Interval(id='update', n_intervals=0, interval=1000*5)
])

# Indicator Graph
@app.callback(
    Output('indicator-graph', 'figure'),
    Input('update', 'n_intervals')
)
def update_graph(timer):
    dff_rv = dff.iloc[::-1]
    day_start = dff_rv[dff_rv['date'] == dff_rv['date'].min()]['rate'].values[0]
    day_end = dff_rv[dff_rv['date'] == dff_rv['date'].max()]['rate'].values[0]

    fig = go.Figure(go.Indicator(
        mode="delta",
        value=day_end,
        delta={'reference': day_start, 'relative': True, 'valueformat':'.2%'}))
    fig.update_traces(delta_font={'size':12})
    fig.update_layout(height=30, width=70)

    if day_end >= day_start:
        fig.update_traces(delta_increasing_color='green')
    elif day_end < day_start:
        fig.update_traces(delta_decreasing_color='red')

    return fig


if __name__=='__main__':
    app.run_server(debug=True, port=3000,use_reloader=False)

Dash is running on http://127.0.0.1:3000/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on